src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReponseRepository::class)]
class Reponse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $reponse;

    #[ORM\Column(type: 'boolean')]
    private $reponse_expected;

    #[ORM\ManyToOne(targetEntity: Question::class, inversedBy: 'reponses')]
    #[ORM\JoinColumn(nullable: false)]
    private $question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString()
    {
        return $this->id;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(string $reponse): self
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function getReponseExpected(): ?bool
    {
        return $this->reponse_expected;
    }

    public function setReponseExpected(bool $reponse_expected): self
    {
        $this->reponse_expected = $reponse_expected;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }
}

src/Form/ReponseType.php
<?php

namespace App\Form;

use App\Entity\Reponse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReponseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reponse')
            ->add('reponse_expected');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reponse::class,
        ]);
    }
}

src/Controller/ReponseController.php
<?php

namespace App\Controller;

use App\Entity\Reponse;
use App\Form\ReponseType;
use App\Repository\ReponseRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reponse')]
class ReponseController extends AbstractController
{
    #[Route('/new', name: 'app_reponse_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReponseRepository $reponseRepository): Response
    {
        $reponse = new Reponse();
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reponseRepository->add($reponse);
            return $this->redirectToRoute('app_reponse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reponse/new.html.twig', [
            'reponse' => $reponse,
            'form' => $form,
        ]);
    }
    #[Route('/{id}/edit', name: 'app_reponse_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reponse $reponse, ReponseRepository $reponseRepository): Response
    {
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reponseRepository->add($reponse);
            return $this->redirectToRoute('app_reponse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reponse/edit.html.twig', [
            'reponse' => $reponse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reponse_delete', methods: ['POST'])]
    public function delete(Request $request, Reponse $reponse, ReponseRepository $reponseRepository, UserRepository $userRepository): Response
    {        
        if ($this->isCsrfTokenValid('delete' . $reponse->getId(), $request->request->get('_token'))) {
            $reponseRepository->remove($reponse);
        }

        return $this->redirectToRoute('app_quizz_edit', ['id' => $reponse->getQuestion()->getCategorie()->getId()]);
    }
}

templates/reponse/_delete_form.html.twig
<form method="post" action="{{ path('app_reponse_delete', {'id': reponse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse.id) }}">
    <button class="delete">Delete</button>
</form>

templates/reponse/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reponse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reponse{% endblock %}

{% block body %}
    <h1>Edit Reponse</h1>

    {{ include('reponse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reponse_index') }}">back to list</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}

templates/reponse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reponse index{% endblock %}

{% block body %}
    <h1>Reponse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>IdQuestion</th>
                <th>Reponse</th>
                <th>ReponseExpected</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reponse in reponses %}
            <tr>
                <td>{{ reponse.id }}</td>
                <td>{{ reponse.idQuestion }}</td>
                <td>{{ reponse.reponse }}</td>
                <td>{{ reponse.reponseExpected ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_reponse_show', {'id': reponse.id}) }}">show</a>
                    <a href="{{ path('app_reponse_edit', {'id': reponse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reponse_new') }}">Create new</a>
{% endblock %}

templates/reponse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reponse{% endblock %}

{% block body %}
    <h1>Create new Reponse</h1>

    {{ include('reponse/_form.html.twig') }}

    <a href="{{ path('app_reponse_index') }}">back to list</a>
{% endblock %}

templates/reponse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reponse{% endblock %}

{% block body %}
    <h1>Reponse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reponse.id }}</td>
            </tr>
            <tr>
                <th>IdQuestion</th>
                <td>{{ reponse.idQuestion }}</td>
            </tr>
            <tr>
                <th>Reponse</th>
                <td>{{ reponse.reponse }}</td>
            </tr>
            <tr>
                <th>ReponseExpected</th>
                <td>{{ reponse.reponseExpected ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reponse_index') }}">back to list</a>

    <a href="{{ path('app_reponse_edit', {'id': reponse.id}) }}">edit</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}